<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../AlyxGamemode/AlyxGamemode.csproj" />
    <PackageReference Include="Websocket.Client" Version="4.4.43" />
    <PackageReference Include="NLua" Version="1.6.0" />
    <Compile Include="../../KiwisCoOpMod/VConsole.cs" Link="VConsole.cs" />
    <Compile Include="../../KiwisCoOpMod/ClientProgram.cs" Link="ClientProgram.cs" />
    <Compile Include="../../KiwisCoOpMod/VConsoleProtocol.cs" Link="VConsoleProtocol.cs" />
    <Compile Include="../../KiwisCoOpMod/StreamWatcher.cs" Link="StreamWatcher.cs" />
    <None Include="../../WorkshopAddon/game/hlvr_addons/kiwimp_alyx/scripts/vscripts/kcom_bootstrap.lua" Link="kcom_bootstrap.lua" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
